Repository SoCo/SoCo, pull requests merged in 2018-05, with the labels that each got.

#596 Fix what broke when the deprecated methods were removed
  soco/core.py
  soco/music_library.py
Labels: Bugfix, Priority 1, Ready

#555 don't throw exception if alarm is not associated to any room
  soco/alarms.py
Labels: Bugfix, Prority 2, Ready

#592 Let DidlMusicAlbum copy _translation from DidlAlbum
  soco/data_structures.py
Labels: Bugfix, Byte size
