Repository SoCo/SoCo, pull requests merged in 2020-11, with the labels that each got.

#753 (Almost) 1000 doc problems. Fixes #752
  doc/api/soco.alarms.rst
  doc/api/soco.compat.rst
  doc/api/soco.config.rst
  doc/api/soco.core.rst
  doc/api/soco.data_structures.rst
  doc/api/soco.discovery.rst
  doc/api/soco.events.rst
  doc/api/soco.exceptions.rst
  doc/api/soco.groups.rst
  doc/api/soco.ms_data_structures.rst
  doc/api/soco.music_library.rst
  doc/api/soco.music_services.accounts.rst
  doc/api/soco.music_services.music_service.rst
  doc/api/soco.plugins.example.rst
  doc/api/soco.plugins.rst
  doc/api/soco.plugins.spotify.rst
  doc/api/soco.plugins.wimp.rst
  doc/api/soco.services.rst
  doc/api/soco.snapshot.rst
  doc/api/soco.soap.rst
  doc/api/soco.utils.rst
  doc/api/soco.xml.rst
  doc/conf.py
  doc/releases/0.14.rst
  doc/releases/0.18.rst
  doc/releases/0.20.rst
  doc/releases/0.8.rst
  soco/alarms.py
  soco/core.py
  soco/data_structures.py
  soco/discovery.py
  soco/events.py
  soco/events_base.py
  soco/events_twisted.py
  soco/groups.py
  soco/music_library.py
  soco/services.py
  soco/snapshot.py
  soco/soap.py
  soco/utils.py
Labels: Bugfix, Docs

#754 Minor documentation fixes
  doc/conf.py
  doc/releases/0.18.rst
  doc/releases/0.19.rst
  doc/releases/0.20.rst
  makefile
Labels: Docs

#733 Network Scan Discovery
  requirements.txt
  soco/discovery.py
  tests/test_discovery.py
Labels: Enhancement

#755 Network scan discovery: add ability to specify the network(s) to scan
  soco/discovery.py
  tests/test_discovery.py
Labels: Enhancement

#756 Add 'get_battery_info' method to the SoCo class
  soco/core.py
Labels: Enhancement

#656 Make zone-group-state cache per-household
  soco/core.py
  soco/discovery.py
  soco/services.py
Labels: Enhancement, Needs revisions
