Repository SoCo/SoCo, pull requests merged in 2020-01, with the labels that each got.

#697 Add Python 2.7 deprecation warning
  soco/__init__.py
Labels: Backward compatibility

#688 Add group volume operations to SoCo
  soco/core.py
  soco/groups.py
  tests/test_core.py
Labels: Enhancement, Needs revisions

#698 Beginning of data structure quirks, fix for missing protocolInfo
  soco/data_structure_quirks.py
  soco/data_structures.py
Labels: Bugfix, Needs review, Needs test
